config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#index'
  get 'predictions' => 'pages#predictions'
  #get 'about' => 'pages#about'
  #get 'result' => 'pages#result'
  post 'update' => 'pages#update'
  get 'view' => 'pages#view'
  get 'compare' => 'pages#compare'
  get 'standings' => 'pages#standings'
  get 'ranking' => 'pages#ranking'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<html>
  <head>
    <title>NFLPredictions</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width", initial-scale=1, maximum-scale=1>

    <div class = "w3-container w3-teal", style = "font-size: 18px"}>
      <div style = "text-align: left">
        <%= link_to('Home', root_path) %>
        &nbsp;
        <%= link_to('Ranking', ranking_path) %>
      </div>
      <div style = "text-align: right">
      <% if user_signed_in? %>
        <%= link_to "#{current_user.username.to_s}", root_url %>
        &nbsp;
        <%= link_to('Logout', destroy_user_session_path, method: :delete) %> 
      <% else %>
        <%= link_to('Login', new_user_session_path)  %>
        &nbsp;
        <!--<%= link_to('Sign up', new_user_registration_path) %>-->
      <% end %>
      </div>
    </div>
  </head>

  <body>
    <%= yield %>
  </body>
</html>